// Code generated by generator/decoder, DO NOT MODIFY MANUALLY

package jt808

import (
	"bytes"
	"fmt"
	message "github.com/francistm/jt808-golang/message"
)

func (messagePack *MessagePack) unmarshalBody(buf []byte) error {
	reader := bytes.NewReader(buf)
	packBody := new(PackBody)

	if messagePack.PackHeader.Package != nil {
		packBody.body = new(message.PartialPackBody)
	} else {
		switch messagePack.PackHeader.MessageID {
		case uint16(0x1):
			packBody.body = new(message.Body0001)

		case uint16(0x200):
			packBody.body = new(message.Body0200)

		case uint16(0x801):
			packBody.body = new(message.Body0801)

		default:
			return fmt.Errorf("unsupported messageId: 0x%.4X", messagePack.PackHeader.MessageID)
		}
	}

	messagePack.PackBody = packBody

	return unmarshalBody(reader, packBody.body)
}
