// Code generated by generator/decoder, DO NOT MODIFY MANUALLY

package jt808

import (
	"bytes"
	"fmt"
	message "github.com/francistm/jt808-golang/message"
)

func (m *MessagePack[T]) unmarshalBody(buf []byte) error {
	var (
		body   any
		reader = bytes.NewReader(buf)
	)

	if m.PackHeader.Package != nil {
		body = new(message.PartialPackBody)
	} else {
		switch m.PackHeader.MessageID {
		case uint16(0x1):
			body = new(message.Body0001)
		case uint16(0x200):
			body = new(message.Body0200)
		case uint16(0x801):
			body = new(message.Body0801)
		default:
			return fmt.Errorf("unsupported messageId: 0x%.4X", m.PackHeader.MessageID)
		}
	}

	m.PackBody = body.(T)

	return unmarshalBody(reader, body)
}
