// Code generated by generator/message, DO NOT MODIFY MANUALLY

package jt808

import message "github.com/francistm/jt808-golang/message"

func (m *PackBody) AsBody0001() *message.Body0001 {
	return m.body.(*message.Body0001)
}

func (m *PackBody) AsBody0200() *message.Body0200 {
	return m.body.(*message.Body0200)
}

func (m *PackBody) AsBody0801() *message.Body0801 {
	return m.body.(*message.Body0801)
}
