package main

import (
	"bytes"
	"io/ioutil"

	. "github.com/dave/jennifer/jen"
	"github.com/francistm/jt808-golang/internal/generator"
)

func main() {
	var messagePackCaseList []Code

	f := NewFile("jt808")
	f.HeaderComment("Code generated by generator/decoder, DO NOT MODIFY MANUALLY")
	messageStructs, err := generator.GetAllMessageStructs()

	if err != nil {
		panic(err)
	}

	for _, messageStruct := range messageStructs {
		code := Case(Lit(messageStruct.HeaderID)).
			Block(
				Id("packBody").
					Dot("body").
					Op("=").
					New(Id("message").Dot(messageStruct.Name)),
			)

		messagePackCaseList = append(messagePackCaseList, code)
		messagePackCaseList = append(messagePackCaseList, Line())
	}

	messagePackCaseList = append(messagePackCaseList, Default().Block(
		Return(
			Qual("fmt", "Errorf").Call(
				Lit("unsupported messageId: 0x%.4X"),
				Id("messagePack").Dot("PackHeader").Dot("MessageID"),
			),
		),
	))

	f.Func().
		Params(
			Id("messagePack").Id("*MessagePack"),
		).
		Id("unmarshalBody").
		Params(
			Id("buf").Index().Byte(),
		).
		Error().
		Block(
			Id("reader").Op(":=").Qual("bytes", "NewReader").Call(Id("buf")),
			Id("packBody").Op(":=").New(Id("PackBody")),
			Line(),
			If(Id("messagePack").Dot("PackHeader").Dot("Package").Op("!=").Nil()).Block(
				Id("packBody").Dot("body").Op("=").New(Qual("github.com/francistm/jt808-golang/message", "PartialPackBody")),
			).Else().Block(
				Switch(Id("messagePack").Dot("PackHeader").Dot("MessageID")).Block(messagePackCaseList...),
			),
			Line(),
			Id("messagePack").Dot("PackBody").Op("=").Id("packBody"),
			Line(),
			Return(
				Id("unmarshalBody").Call(
					Id("reader"),
					Id("packBody").Dot("body"),
				),
			),
		)

	buf := new(bytes.Buffer)

	if err := f.Render(buf); err != nil {
		panic(err)
	}

	if err := ioutil.WriteFile("decoder.gen.go", buf.Bytes(), 0644); err != nil {
		panic(err)
	}
}
