package main

import (
	"os"
	"path"

	. "github.com/dave/jennifer/jen"
	"github.com/francistm/jt808-golang/internal/generator"
)

func main() {
	f := NewFile("message")
	f.HeaderComment("Code generated by generator/decoder, DO NOT MODIFY MANUALLY")
	mesgDecls, err := generator.ParseMesgDecls()

	if err != nil {
		panic(err)
	}

	genMesgBodyIface(f, mesgDecls)
	genNewPkgBodyFromMesgId(f, mesgDecls)

	cwd, err := os.Getwd()

	if err != nil {
		panic(err)
	}

	filePath := path.Join(cwd, "message", "mesg_pack.gen.go")

	outFile, err := os.OpenFile(filePath, os.O_CREATE|os.O_RDWR|os.O_TRUNC, 0644)

	if err != nil {
		panic(err)
	}

	if err := f.Render(outFile); err != nil {
		panic(err)
	}
}
